backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored

collections:
  - name: "locations"
    label: "Bar Locations"
    description: "Website Configuration for each location"
    create: true
    delete: false
    extension: "json"
    folder: "data/locations"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Team Name"
        name: "team"
        widget: "string"
      - label: "URL Identifier"
        name: "title"
        hint: "url identifier such as ny, la, ftl"
        widget: "string"
      - label: "Show Locker Room"
        name: "locker"
        widget: "boolean"
      - label: "Contact Information"
        name: "contacts"
        widget: "object"
        collapsed: true
        fields:
          - label: "Address Line 1"
            name: "address1"
            widget: "string"
          - label: "Address Line 2"
            name: "address2"
            widget: "string"
          - label: "Phone Number"
            name: "phone"
            widget: "string"
          - label: "Email Address"
            name: "email"
            widget: "string"
          - label: "Timezone"
            name: "timezone"
            widget: "string"
          - label: "Maps Link"
            name: "maps"
            widget: "string"
          - label: "Location Hours"
            name: "hours"
            summary: "{{fields.days}}: {{fields.hours}}"
            minimize_collapsed: true
            widget: "list"
            fields:
              - label: "Days"
                name: "days"
                widget: "string"
              - label: "Hours"
                name: "hours"
                widget: "string"
      - label: "Recurring Events"
        name: "recurring"
        widget: "list"
        minimize_collapsed: true
        fields:
          - label: "Event Name"
            name: "name"
            widget: "string"
          - label: "Destination URL"
            name: "url"
            required: false
            widget: "string"
          - label: "Weekday"
            name: "weekday"
            widget: "number"
            value_type: "int"
            min: 1
            max: 7
            hint: "1 for Monday, 7 for Sunday"
          - label: "Start Time"
            default: ""
            name: "start"
            required: false
            widget: "datetime"
            time_format: true
            date_format: false
            format: "HH:mm"
          - label: "End Time"
            name: "end"
            default: ""
            required: false
            widget: "datetime"
            time_format: true
            date_format: false
            format: "HH:mm"
      - label: "Events"
        name: "events"
        widget: "list"
        minimize_collapsed: true
        fields:
          - label: "Event Name"
            name: "name"
            widget: "string"
          - label: "Destination URL"
            name: "url"
            required: false
            widget: "string"
          - label: "Date"
            name: "date"
            widget: "datetime"
            time_format: false
            format: "YYYY-MM-DD"
            date_format: true
          - label: "Start Time"
            default: ""
            name: "start"
            required: false
            widget: "datetime"
            time_format: true
            date_format: false
            format: "HH:mm"
          - label: "End Time"
            name: "end"
            default: ""
            required: false
            widget: "datetime"
            time_format: true
            date_format: false
            format: "HH:mm"
      - label: "Sports Leagues"
        name: "leagues"
        widget: "list"
        minimize_collapsed: true
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Image"
            name: "img"
            widget: "image"
            required: false
          - label: "Slug"
            name: "slug"
            hint: "Slug is a unique identifier for this league's url"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "text"
          - label: "Website"
            name: "website"
            widget: "string"
          - label: "Section"
            name: "section"
            widget: "string"
      - label: "Menu"
        name: "menu"
        widget: "list"
        fields:
          - label: "Section"
            name: "section"
            widget: "string"
          - label: "Food Items"
            name: "items"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "text"
      - label: "Home Page Posters"
        name: "posters"
        widget: "list"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Image"
            name: "img"
            widget: "image"
          - label: "Link"
            name: "link"
            widget: "string"
            required: false
      - label: "Social Links"
        name: "socials"
        widget: "list"
        fields:
          - label: "URL"
            name: "url"
            widget: "string"
