backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accessed from the server

collections:
  - name: "contacts"
    label: "Contacts"
    description: "Contact information for each location"
    extension: "json"
    files:
      - label: "Locations"
        name: "locations"
        file: "data/contact.json"
        fields:
          - label: "Location"
            name: "location"
            widget: "string"
            pattern: ["ny|la|ftl", "Must be ny, la, or ftl."]
          - label: "Address Line 1"
            name: "address1"
            widget: "string"
          - label: "Address Line 2"
            name: "address2"
            widget: "string"
          - label: "Phone Number"
            name: "phone"
            widget: "string"
          - label: "Email Address"
            name: "email"
            widget: "string"
          - label: "Location Hours"
            name: "hours"
            widget: "list"
            fields:
              - label: "Days"
                name: "days"
                widget: "string"
              - label: "Hours"
                name: "hours"
                widget: "string"