backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Where media files will be stored

collections:
  - name: "locations"
    label: "Bar Locations"
    description: "Website Configuration for each location"
    create: true
    extension: "json"
    folder: "data/locations"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "URL Identifier"
        name: "title"
        description: "url identifier such as ny, la, ftl"
        widget: "string"
      - label: "Contact Information"
        name: "contacts"
        widget: "object"
        fields:
          - label: "Address Line 1"
            name: "address1"
            widget: "string"
          - label: "Address Line 2"
            name: "address2"
            widget: "string"
          - label: "Phone Number"
            name: "phone"
            widget: "string"
          - label: "Email Address"
            name: "email"
            widget: "string"
          - label: "Location Hours"
            name: "hours"
            widget: "list"
            fields:
              - label: "Days"
                name: "days"
                widget: "string"
              - label: "Hours"
                name: "hours"
                widget: "string"